name: CI Webapck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Tests
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    
      run: |
        npm install && npm run test
